# Generated by Django 4.1.2 on 2022-11-05 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_salesappuser_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, unique=True, verbose_name='Movie Name')),
            ],
        ),
        migrations.CreateModel(
            name='MovieTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_timing', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Theatres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=50, unique=True, verbose_name='Theatre Name')),
                ('ticket_price', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTheatreStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.movies')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.theatres')),
                ('time_slots', models.ManyToManyField(to='salesapp.movietimeslots')),
            ],
        ),
    ]
