# Generated by Django 4.1.2 on 2022-11-09 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_movies_movietimeslots_theatres_movietheatrestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.PositiveIntegerField()),
                ('min_seats', models.PositiveIntegerField()),
                ('max_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='theatres',
            name='ticket_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='theatres',
            name='total_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.IntegerField(choices=[(1, 'In Progress'), (2, 'Success')], default=1)),
                ('total_seats_booked', models.PositiveIntegerField()),
                ('seats_booked', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('total_price', models.PositiveIntegerField()),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.theatres')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.movietimeslots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
