# Generated by Django 4.1.2 on 2022-11-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_applicationsettings_alter_theatres_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatus',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
