# Generated by Django 4.1.2 on 2022-11-10 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0005_alter_bookingstatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatus',
            name='booking_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 11, 10, 0, 27, 8, 696638, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='date',
            field=models.DateField(),
        ),
    ]
