# Generated by Django 4.1.2 on 2022-11-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0006_bookingstatus_booking_date_alter_bookingstatus_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstatus',
            name='id',
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='booking_id',
            field=models.CharField(default='3GL1ljxAWv1JtGUBQZ49A8kit8RIBy7M', max_length=100, primary_key=True, serialize=False),
        ),
    ]
