# Generated by Django 4.1.2 on 2022-11-10 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0007_remove_bookingstatus_id_bookingstatus_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatus',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.movies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='booking_id',
            field=models.CharField(default='cGd4ehqSRSiLVS5KARgyzUYNwzH9J8Md', max_length=100, primary_key=True, serialize=False),
        ),
    ]
