# Generated by Django 4.1.2 on 2022-11-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0008_bookingstatus_movie_alter_bookingstatus_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatus',
            name='booking_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
