# Generated by Django 4.1.2 on 2022-11-10 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0009_alter_bookingstatus_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('cvv', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('expiry', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
