# Generated by Django 4.1.2 on 2022-11-13 18:19

from django.db import migrations, models
import salesapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0011_alter_userpaymentinformation_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatus',
            name='booking_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[salesapp.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(max_length=50, unique=True, validators=[salesapp.validators.validate_field], verbose_name='Movie Name'),
        ),
        migrations.AlterField(
            model_name='salesappuser',
            name='email',
            field=models.EmailField(max_length=255, validators=[salesapp.validators.validate_email], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='salesappuser',
            name='full_name',
            field=models.CharField(max_length=100, validators=[salesapp.validators.validate_field], verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='salesappuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[salesapp.validators.validate_field_nospace], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='theatres',
            name='theatre_name',
            field=models.CharField(max_length=50, unique=True, validators=[salesapp.validators.validate_field], verbose_name='Theatre Name'),
        ),
        migrations.AlterField(
            model_name='userpaymentinformation',
            name='expiry',
            field=models.CharField(max_length=5, validators=[salesapp.validators.validate_field]),
        ),
    ]
